name: caladan.cc
favicon: null
layout_spectrum: 0.68793
typography_spectrum: 0.63359
title: caladan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77356508-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#5488b7'
    - '#172844'
    - '#89bdec'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
