name: caladan.cc
favicon: null
layout_spectrum: 0.09063
typography_spectrum: 0.63359
title: YOUR NEXT HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77356508-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22477b'
    - '#bbc6d6'
    - '#6b82a0'
    - '#6cbd45'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
