name: CALADAN.CC
favicon: null
layout_spectrum: 0.68793
typography_spectrum: 0.66786
title: CALADAN Companies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#5488b7'
    - '#172844'
    - '#89bdec'
  brandStrength: 0.4617455101106316
  lightness: 0.20331133739091456
  saturation: 0.7721838420256972
  rhythmicContrast: 0.5
purpose: []
