name: CALADAN.CC
favicon: null
layout_spectrum: 0.26592823793180287
typography_spectrum: 0.7057344017084688
title: CALADAN Companies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4617455101106316
  lightness: 0.20331133739091456
  saturation: 0.7721838420256972
  rhythmicContrast: 0.29942471208050847
purpose: []
